### PR TITLE
Initial build

### PR DESCRIPTION
**Pull request by kjmahalingam**
This branch creates the initial implementation of the fhir_smart gem, for SMART-on-FHIR testing of a FHIR server.

### CODE REVIEW

**Comment by jawalonoski** [comment]
What is the purpose of this? A lot of the code seems duplicative of the FHIR scorecard. I see things like tests for smoking status or vital signs -- which aren't really covered by the SMART-on-FHIR specification.

**Comment by kjmahalingam** [comment]
To address the comment about the purpose of this gem:

The gem was created to directly copy the functionality of the original SMART on FHIR Sinatra app and make these tests portable. Currently, the smart-on-fhir branch of the main Crucible app is using this gem to run the SMART on FHIR tests in Rails. With this functionality, the Sinatra app is no longer necessary, as all the functionality for SMART on FHIR testing will be implemented in Rails in the main Crucible app.

As far as the tests about smoking status and vital signs go, I brought these tests in from the original Sinatra app. Since they were initially included in the Sinatra app, I had assumed that these tests were still desirable; however, if they are irrelevant, I can certainly remove them.

**Comment by arscan** [comment]
I can't speak to the smoking/vital signs, but the plan for migrating the SMART-on-FHIR tests into crucible was to encapsulate them in a gem as a first step, like plan_executor, and fhir_scorecard.  Once we have it running completely in the rails environment, and @kjmahalingam had more experience with SMART and Crucible, he would look about perhaps having tighter integration with the rest of Crucible.

**Comment by jawalonoski** [comment]
OK, but it doesn't look like you actually do any SMART authentication here either. So, this is just tests. I guess I need to think about this for a little bit.

**Comment by kjmahalingam** [comment]
Yes, the OAuth2 authentication process is all included in the smart-on-fhir branch of the main Crucible app. The initial plan was to simply place tests in this gem to make the process modular, and have Crucible itself do the authentication process. I was waiting to open a pull request on the smart-on-fhir branch of Crucible until the multiversion support was merged in, as we discussed at a meeting late last week. To explain a bit, though, the smart-on-fhir Crucible branch implements the authentication procedure exactly as the original Sinatra app did, then uses this gem to run the tests once authorized. Is there anything in particular that you would like me to edit about this gem?

**Pull request closed without merging**
